-- Deploy sauropode:creationdb to pg

BEGIN;

DROP TABLE IF EXISTS "animal","periode", "animal_periode","lieu","animal_lieu","alimentation","animal_alimentation", "anecdote";


CREATE TABLE "animal" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    nom_scientifique TEXT NOT NULL,
    etymologie TEXT NOT NULL,
    espece TEXT NOT NULL,
    hauteur NUMERIC(5,1),
    longueur NUMERIC (5,1),
    poids NUMERIC(5,1),
    decouverte INT
    );



CREATE TABLE "periode" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periode TEXT,
    sous_periode TEXT,
    dates TEXT
);

CREATE TABLE "animal_periode" (
    "animal_id" INTEGER,
    FOREIGN KEY ("animal_id") REFERENCES "animal"("id"),
    "epoque_id" INTEGER,
    FOREIGN KEY ("epoque_id") REFERENCES "periode"("id")
    );

CREATE TABLE "lieu"(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lieu TEXT
    );

CREATE TABLE "animal_lieu" (
    "animal_id" INTEGER NOT NULL,
    FOREIGN KEY ("animal_id") REFERENCES "animal"("id"),
    "lieu_id" INTEGER NOT NULL,
    FOREIGN KEY ("lieu_id") REFERENCES "lieu"("id")
    ); 


CREATE TABLE "alimentation"(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alimentation TEXT
    );

CREATE TABLE "animal_alimentation" (
    animal_id INTEGER NOT NULL,
    FOREIGN KEY ("animal_id") REFERENCES "animal"("id"),
    type_id INTEGER NOT NULL,
    FOREIGN KEY ("type_id") REFERENCES "alimentation"("id"));


CREATE TABLE "anecdote"(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "concern" INTEGER NOT NULL,
    FOREIGN KEY ("concern") REFERENCES "animal"("id"),
    histoires TEXT
    );
-- XXX Add DDLs here.


COMMIT;
